apiVersion: v1
kind: Service
metadata:
  name: redis-test-master-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis-test
    app.kubernetes.io/name: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31000
