spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: my-redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-16.4.0
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31000
